name: cProfile
version: 1.1.3
author: ClimpyX
main: com.climpy.profile.ProfilePlugin
commands:
  user:
    aliases: [rankdata]
  setrank:
    aliases: [rankset, rank, rankayarla]
  listrank:
    aliases: [ranklist]
  setsymbol:
    aliases: [symbolset]
  symbol:
    aliases: [sembol, semboller]
  coins:
    aliases: [kredi]
  staff:
    aliases: [staffmode]
  freeze:
    aliases: [dondur]
  list:
  broadcast:
  day:
  night:
  world:
  createworld:
  deleteworld: